name: Sync Repo
on: 
  schedule:
    - cron: '0 14 * * *'
    # scheduled for 21:00 GMT+7 everyday
  workflow_dispatch:

jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: master            # set the branch to merge to
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}
      - name: Setup committer
        run: |
          git config --global user.email "tuthanika@gmail.com"
          git config --global user.name "tuthanika"
      - name: Merge Upstream
        run: |
          set +x
          git remote add -f upstream "https://github.com/yt-dlp/yt-dlp" &&
          git remote -v &&
          git branch --all &&
          git config --list &&
          git checkout master
          echo "Upstream log: "
          git log --graph --oneline upstream/master | head -n 30
          echo "Our log: "
          git log --graph --oneline master | head -n 10
          echo "Merge fork point: $(git merge-base --fork-point master upstream/master)"
          git merge upstream/master -m "AutoMerge-$(date '+%Y%m%d-%H%M%S')"
          git merge --abort || true;
          echo "After Rebase:"
          git log --graph --oneline master | head -n 30
          echo "Re-tagging master!"
          git checkout $(git rev-parse HEAD); git branch -f master HEAD; git checkout master
      #- name: Prepare to push  
      #  run: git branch -f master
      - name: Push changes
        run: git push https://${{ github.token }}@github.com/tuthanika/ty-dlp.git
      - uses: gautamkrishnar/keepalive-workflow@v1 # using the workflow with default settings
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 0
